### ISSUE TITLE
fail to run yo react-webpack-redux

### ISSUE THREAD

**Issue by gnesher** [stylesuxx/generator-react-webpack-redux#8]
Just followed instructions and installed yo (and various dependencies) then ran the generator. Getting the following errors:

```
GUYs-MacBook-Pro:test guynesher$ yo react-webpack-redux

/usr/local/lib/node_modules/generator-react-webpack-redux/generators/app/index.js:2
let generator = require('yeoman-generator');
^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object._storeAsPath.Object.defineProperty.get [as react-webpack-redux:app] (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:40:23)
    at Store.get (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:64:35)
    at Environment.get (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:260:16)
    at Environment.create (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:292:24)
```

**Comment by stylesuxx** [comment]
Interesting. Strict mode is set in this file. Can you provide me with more information, which version of node are you running on?

```Bash
node --version
yo --version
npm --version
```

**Comment by kirstywilliams** [comment]
Ran into the same issue. Fixed by updating node version.

**Comment by stylesuxx** [comment]
Which node version did you have before the update?

**Comment by kirstywilliams** [comment]
Seriously outdated one. 0.10.36

**Comment by stylesuxx** [comment]
Wow, OK then ;-)
Do you think I should adapt the README to make it more clear that node version >= 4.0 is needed?

**Comment by stylesuxx** [comment]
Closing this down for now.
